### ISSUE TITLE
add instructions to install `just` and `cargo-hack` to docs

### ISSUE THREAD

**Issue by dmackdev** [plabayo/rama#129]
When following the `CONTRIBUTING.md` instructions and trying to run the test command `just qa`, I had to install the missing tools `just` and `cargo-hack`.

I suggest adding installation instruction steps for these tools to the `CONTRIBUTING.md` doc.

**Comment by GlenDC** [comment]
Great idea. I can add it tonight, unless you prefer to do it yourself? Both ok for me!

Thinking about it, it might be overkill for developers to run ‘just qa’, especially on regular computers can take some time.

I think I’ll recommend to just run ‘just test’ or something like it. But I’ll add that you can also run just qa for those that want to run pretty much all tests (except version/platform). In that paragraph I can add install instructions for those tools.

thx again for the report and great feedback/suggestion. Much appreciated!

**Comment by dmackdev** [comment]
Might make more sense for you to take this one, if you are planning to make other amendments to the docs around `just` command usage?

Equally I am happy to add a couple steps to `CONTRIBUTING.md`.

**Comment by GlenDC** [comment]
Ok I’ll add it in some hours myself then. I agree with you there.

**Comment by GlenDC** [comment]
Closed in https://github.com/plabayo/rama/commit/fa4be34c48519d291235bd6bc44f56c1fd56a747.
