### ISSUE TITLE
support and release rama-cli also via `homebrew` (macOS)

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#132]
Guide: <https://docs.brew.sh/Adding-Software-to-Homebrew>

As a first step this can be done manually via a script, but ideally it is eventually (or immediately) (semi-/full-) automated as a Github Action.

**Comment by GlenDC** [comment]
No because there is no real release yet. As such this was marked as v0.3.
This (and the other release-like tickets) are for the `rama` cli tool, which will be in a way a showcase for rama,
but also good enough for common proxy use cases (e.g. as a replacement for `squid` or other proxy software.

I can make a pre-release if you need that of 0.2 with `rama` cli. Not sure how useful that is though to already tackle this ticket. But at the same time do not mind doing that, if this is the kind of work you want to pick up, I'm happy to have it be done. Do let me know.

**Comment by AlvinKuruvilla** [comment]
No I agree, if 0.2 is too early for a release I can always wait on this ticket . In the meantime, I could take a stab at #128 or another one if you would rather I prioritize something else.

**Comment by GlenDC** [comment]
@AlvinKuruvilla that would be very much appreciated, I have a feeling it is a story right up your alley. I added the steps and goals of that issue in a new comment just now: <https://github.com/plabayo/rama/issues/128#issuecomment-2035433959>

Take into account that this is a pretty involved story that will require time/work and has higher then easy difficulty. That said I Do think you'll be able to handle it, as long as you have the desire and possibility to spend the time on it.

If you do consider to ambitious / time-intensive to your liking, then #23, #44 and #45 are also still available. Feel free to also instead pick on of these. Either way the choice is yours and I'll respect whatever that choice is. Take care and thanks for the interest, motivation and effort!
