### ISSUE TITLE
replace futures crate dep with futures_lite

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#150]
docs: https://docs.rs/futures-lite/latest/futures_lite/index.html

Remark: `join_all` is not there, but given we only join two futures in the usage found within rama, we can just replace our `join_all` usage with `futures::future::zip`.

**Comment by dalprahcd** [comment]
Hello @GlenDC,

I am looking for opportunities to contribute (and learn) to Rust open source, can I try working on this issue?

**Comment by GlenDC** [comment]
Sure thing @dalprahcd . Go for it, it's all yours. Welcome and thank you for your interest. If you need guidance, help or want to discuss something, you can reach out here on in your PR once you have one. Take care and good luck.
