### ISSUE TITLE
expand support to hijack based on context data

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#328]
e.g. callback, or Eq Value (e.g. UserID), stuff like that

**Comment by GlenDC** [comment]
Could be called an `ExtensionMatcher`, which can be created with two inputs:

- or by using a constant `T` which is `Eq`
- or by using a fn callback which is called if the value `T` is there

**Comment by calebbourg** [comment]
Hello @GlenDC  I would like to pick this up if it has not already been spoken for.

**Comment by GlenDC** [comment]
All yours if you want to go for it @calebbourg , welcome and nice to e-meet you.

Feel free to open a PR in any state, in case you want me to provide early feedback, or need guidance. Should the information not be clear or you might have any questions do let me know. I'm here for you.

**Comment by calebbourg** [comment]
@GlenDC Thank you very much. Yes, could you elaborate a bit on what is desired here? Perhaps point to the correct part of the project to get started?

**Comment by GlenDC** [comment]
In `rama` there is a `Matcher` interface for which you can find docs at <https://ramaproxy.org/docs/rama/matcher/trait.Matcher.html>

It can be used for all kinds of purposes, but for example the `Hijack` layer (https://ramaproxy.org/docs/rama/layer/struct.HijackLayer.html) also uses this to decide when to use the hijack service and when the regular inner server.

There are some use cases on which you might just want to match based on an extension, be it equality or with a custom callback, that are pretty easy to serve with a `Matcher` implementation for a new struct that you'll introduce called `ExtensionMatcher`. Can be added at https://github.com/plabayo/rama/tree/main/rama-core/src/matcher under a file called `ext.rs` or so.

This way you could achieve for example that in case someone would have the following kind of setup:

```
struct MyMarker;

ExtensionMatcher::constant(MyMarker);
// this will match in case `(*Context<S>)::get::<MyMarker>().map(|v| v == c).unwrap_or_default()`


// You can however also create it with a callback, e.g.
ExtensionMatcher::fn(|marker: &MyMarker| true)
```

Hopefully this gets the idea across.

**Comment by calebbourg** [comment]
@GlenDC Thank you very much for the direction. I opened a PR that I would be very grateful for feedback on at your convenience https://github.com/plabayo/rama/pull/346

The tests I have written do not pass. I'm not 100% that I am understanding the concepts involved correctly and how these functions are meant to be used but I thought this would serve as a good place to start.

**Comment by GlenDC** [comment]
I left my feedback for you in the PR @calebbourg. You were pretty close though!

**Comment by GlenDC** [comment]
Closed by #346 by @calebbourg. Thanks and congratulations with your first Rama contribution! 🎉👏

**Comment by calebbourg** [comment]
@GlenDC Thank you very much! I'd love to make another contribution. I've looked through the other issue but thought perhaps there may be one or more that you might recommend that would provide value to the project?

**Comment by GlenDC** [comment]
Another idea @calebbourg can be to use Rama or read more through the code and notice things that can use contributions:

- can be quality of life stuff such as trait implementations, small improvements
- can be typo fixes
- can be documentation enhancements/fixes/additions
- can be examples
- can be all kind of other improvements
- and of course can be also bug reports and fixes, should those be there

Given that these are not yet clearly defined (as you would be the one finding them), might be best to first discuss them over either Email (glen@plabayo.tech) or Discord (see README), as it might be not something that is desired to be done or might require some quick discussion. If you are more certain of whatever it is that you found it can also be immediately as an issue, so a bit up to you how you handle those things.

Either way thank you once again for your contribution and for your further interest in Rama :)

**Comment by calebbourg** [comment]
Ok great thank you so very much!
