### ISSUE TITLE
add "Deny All" Dns Resolver 

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#329]
A <https://ramaproxy.org/docs/rama/dns/trait.DnsResolver.html> implementation which returns an error for any incoming request. Can be named `DenyAllDns`.

**Comment by parkma99** [comment]
Hi, I am from `[This Week in Rust](https://this-week-in-rust.org/)`, I would like to work it.

**Comment by GlenDC** [comment]
Sure thing. How I see it is that it's basically an empty struct `DenyAllDns` which always returns an error, e.g. `DnsDeniedError` (can be made with `rama_utils::macros::error::static_str_error!`). And then implement the `DnsResolver` trait.

That's how I see it, but feel free to do it differently if you see another approach :)

Nice to meet you and thank you for your interest.

**Comment by GlenDC** [comment]
Closed with https://github.com/plabayo/rama/pull/344 by @parkma99 
Thanks 🥳 !
