### ISSUE TITLE
figure out how we can explicitly allow Anonymous users in layers such as ProxyAuth

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#330]
Currently these require an <https://ramaproxy.org/docs/rama/net/user/auth/trait.Authority.html> which on its turns requires a <https://ramaproxy.org/docs/rama/http/headers/authorization/trait.Credentials.html> and that is the issue for supporting Anonymous users.

We essentially need to be able to support an authority without it being hard-linked to a credential. This way we could easily support an Authority such as (NoAuthority == No UserId == Anonymous)

**Comment by calebbourg** [comment]
@GlenDC I've looked a bit at the code involved here and wanted to put my thoughts on paper to see if this is at all in line with what you might have envisioned. If I'm way off that's ok too and I can take a look at other things when they come up :). I realize this is low priority and I want to respect your time. I very much appreciate all of the support.

My first thought (in somewhat pseudo code) would be to extract the credential handling into it's own trait something like

```rust
pub trait CredentialHandler<T> {
    fn validate_credentials(&self, credentials: &Self) -> bool;
}
```

and then the implementations for [Basic](https://github.com/plabayo/rama/blob/main/rama-net/src/user/credentials/basic.rs)

```rust
// move the responsibility of parsing here as well

impl<T: UsernameLabelParser>  CredentialHandler for Basic {
    fn validate_credentials(&self, credentials: &Self) -> bool {
        let username = credentials.username();
        let password = credentials.password();

        if password != self.password() {
            return false;
        }

        let mut parser_ext = Extensions::new();
        let username = match parse_username(&mut parser_ext, T::default(), username) {
            Ok(t) => t,
            Err(err) => {
                tracing::trace!("failed to parse username: {:?}", err);
                return if self == credentials {
                    ext.insert(UserId::Username(username.to_owned()));
                    true
                } else {
                    false
                };
            }
        };

        if username != self.username() {
            return false;
        }

        ext.extend(parser_ext);
        ext.insert(UserId::Username(username));
        true
    }
}
```

and 

```rust
impl AuthoritySync<Basic> for Basic {
    fn authorized(&self, ext: &mut Extensions, credentials: &Basic) -> bool {
        self.validate_credentials(credentials)
    }
}
```

With this approach I hit an decision [here](https://github.com/plabayo/rama/blob/main/rama-http/src/layer/proxy_auth.rs#L149-L155) 

```rust
impl<A, C, L, S, State, ReqBody, ResBody> Service<State, Request<ReqBody>>
    for ProxyAuthService<A, C, S, L>
where
    A: Authority<C, L>,
    C: Credentials + Clone + Send + Sync + 'static,
    S: Service<State, Request<ReqBody>, Response = Response<ResBody>>,
    L: 'static,
    ReqBody: Send + 'static,
    ResBody: Default + Send + 'static,
    State: Clone + Send + Sync + 'static,
{
    type Response = S::Response;
    type Error = S::Error;

    async fn serve(
        &self,
        mut ctx: Context<State>,
        req: Request<ReqBody>,
    ) -> Result<Self::Response, Self::Error> {

      // extracting credentials based on the type of Credentials
        if let Some(credentials) = req
            .headers()
            .typed_get::<ProxyAuthorization<C>>()
            .map(|h| h.0)
            .or_else(|| ctx.get::<C>().cloned())
        {
            // authorizing
            if let Some(ext) = self.proxy_auth.authorized(credentials).await {
                ctx.extend(ext);
                self.inner.serve(ctx, req).await
            } else {
                Ok(Response::builder()
                    .status(StatusCode::PROXY_AUTHENTICATION_REQUIRED)
                    .header(PROXY_AUTHENTICATE, C::SCHEME)
                    .body(Default::default())
                    .unwrap())
            }
        } else {
            Ok(Response::builder()
                .status(StatusCode::PROXY_AUTHENTICATION_REQUIRED)
                .header(PROXY_AUTHENTICATE, C::SCHEME)
                .body(Default::default())
                .unwrap())
        }
    }
}
```

If I understand this correctly, the serve method requires the type information of a `Credentials` implementer to grab the data from the request headers.
So it seems like we would need two `Serve` implementations for `ProxyAuthService`. 
- One that extracts and uses `Credentials` and has the information to do so
- One that doesn't care about `Credentials` and can support `Anonymous` as an `Authority` implementer


Another potential alternative was to just implement `Credentials` for `Anonymous` in such a way that it's a no-op. I haven't really gone down that train of thought much as I assume that's what you're hoping to avoid here.

**Comment by GlenDC** [comment]
You are indeed a bit off on the wrong footing but I wouldn't let that immediately discourage you. Would be good to get some more folks deeper into the trenches here, so might be a good training ground this issue for you.

A custom `Credentials` implementation could be an approach but that would be a bit nasty as you would still need to have a scheme and such or have it be nil, but either way bit odd.

Thanks for diving into this issue though, I realize again why the `Credentials` is linked, it's because we also link it to a header. There might be ways to untangle that mess but I think it's good like it is as that's the strength of that layer. That it's so easy, you don't need to think about much. For something more advanced or custom you can write easily your own layer.

As such while I was writing potential other roads I suddenly realized we can just as well solve it very easy on a per-layer basis, there are only 2 of them in rama:

- https://ramaproxy.org/docs/rama/http/layer/proxy_auth/struct.ProxyAuthLayer.html (for proxy auth)
- https://ramaproxy.org/docs/rama/http/layer/auth/struct.AsyncRequireAuthorizationLayer.html (for regular auth)

With that in mind I think this issue (#330) can be solved in following way:

1. add `Anonymous` to <https://ramaproxy.org/docs/rama/net/user/enum.UserId.html>, might break some code so that will have to be fixed to to take into account the new variant
2. have a `bool` in these 2 layers `allow_anonymous` that can be set in the layer using `with_allow_anonymous(mut self, bool) -> self` and `set_allow_anonymous(&mut self, bool) -> &mut Self`. Same for the service implementations that are created by these layers
3. that bool is then used in the service to check it. If and only if the header used by that layer is absent and the bool is true we will authorize the user as `UserID::Anonymous`

It's a fairly trivial resolution and still gets the job done. Because I feel any other kind of approach kinda defeats the purpose of these layers. These layers are really just meant as basic approaches to authorization. For any secure-sensitive env you probably anyway want a much more advanced kind of layer so there's no point in making this basic case more difficult to use than it is today.

**Comment by calebbourg** [comment]
Thank you, that makes sense to me and I appreciate the response! How would you feel about me taking a spin at the solution you outlined? Alternatively I'm happy to wait and see what others might bring to the conversation in the future.

**Comment by calebbourg** [comment]
Thank you.  Very grateful for your time.

**Comment by calebbourg** [comment]
I tried to take two different paths with this:
- Introducing a new struct `AuthorizationContext` in https://github.com/plabayo/rama/pull/349 based on your suggestion
  - The way I approached it requires `AuthorizationContext` to become part of the public interface. I was not sure how best togo about making that hidden. (May very well have not fully understood your vision there)
- Introducing a new trait `AllowAnonymous`. in https://github.com/plabayo/rama/pull/351
  - in some ways this feels less awkward to me (compared to the path I went down in the other PR) but it also, as is, requires `AllowAnonymous` to be a public trait.

**Comment by calebbourg** [comment]
Thank you! For your patience with my learning through this as well and for all of the kind words, help, and explanation.
I was not sure on the alternative approach I tried but kind of working my way through how best to express   ideas in Rust. 
 I appreciate you taking the time to consider my thought process and giving me feedback. It helps tremendously with my learning process :)

**Comment by GlenDC** [comment]
Resolved by @calebbourg in https://github.com/plabayo/rama/pull/349.
Thank you very much for this contribution.

**Comment by calebbourg** [comment]
Thank you so very much!
