### ISSUE TITLE
support vec/array impl for DnsResolver

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#332]
It would allow you to chain multiple dns resolvers together, where it would try the next in case of error.

Note that this should not be used just to use multiple dns providers, as that can be configured already in a single resolver (eg Hickory)

**Comment by GlenDC** [comment]
@parkma99 is picking this up

**Comment by GlenDC** [comment]
This issue is available once again. Feel free to start from scratch or use @parkma99's original attempt as a starting point. All the same, whatever works best for the one picking this issue up.

**Comment by NOOMA-42** [comment]
> This issue is available once again. Feel free to start from scratch or use @parkma99's original attempt as a starting point. All the same, whatever works best for the one picking this issue up.

I'd like to pick this up

**Comment by GlenDC** [comment]
All yours @NOOMA-42 , let me know if you need guidance, help or feedback
