### ISSUE TITLE
Add SocketAddress to rama-net

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#358]
It's pretty much like Authority from the same rama-net package (https://ramaproxy.org/docs/rama/net/address/index.html)

But it is a IpAddr Port (u16) pair, so IpAddr instead of Host.

We can also make it convertible to and from std's SocketAddr.

This type is convenient if you want to enforce it to be a socket compatible addr, which Authority can't do for you.

**Comment by hafihaf123** [comment]
Hello,

I’m the one who reached out about the other issue (#357) and I appreciate you suggesting this one as a better starting point. I’d love to work on this issue as my first contribution to the project. As I mentioned before, I’m new to Rust and open-source contributions, so I might need some guidance along the way, but I’m eager to learn and give it my best effort.

Thank you for offering to mentor me, and I look forward to working on this!

**Comment by GlenDC** [comment]
Hi the issue is assigned to you and all yours. Feel free to open a PR as soon as you are stuck or need guidance, if not ready of course.

Is the issue description clear to you? You can essentially start by copying the authority code as mentioned in the description and replace host with ip_addr. Following that path should get you mostly there.

Do let me know if you are stuck anywhere or need to talk some things through or are in need of guidance :)

**Comment by Muktarsadiq** [comment]
Hello Good day, i'd also love. to contribute to this project, i'm also a junior Rust dev and this is going to be my first open source contribution, If you don’t mind i'd need guidance on how to proceed.

**Comment by GlenDC** [comment]
@Muktarsadiq welcome. As @hafihaf123 is already working on this issue I suggest you to pick up something else.

I just created a new issue, which is similar in scope and difficulty. If you would be willing to pick that up @Muktarsadiq you are free to comment on the issue https://github.com/plabayo/rama/issues/360 to claim it. I'm available as a mentor for that as well, and feel free to open a PR as soon as you're stuck, feel ready or want feedback of any kind.
