### ISSUE TITLE
provide constants for common (network) hosts to rama-net's Host

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#363]
These constants can be added as associated constants to `Host` in https://github.com/plabayo/rama/blob/c7f10e9efd0a89a6f384debd13eda1fa1ece3008/rama-net/src/address/host.rs#L13, e.g. as an impl block:

```rust
impl Host {
     /// description
     const NAME: Self = VALUE;

     /// ...
}
```

You can do so for the following list of common hosts:

Name | Value | Description
-- | -- | --
LOCALHOST_IPV4 | 127.0.0.1 | Local loopback address (IPv4)
LOCALHOST_IPV6 | ::1 | Local loopback address (IPv6)
LOCALHOST_NAME | localhost | Local loopback name
DEFAULT_IPV4 | 0.0.0.0 | Default address, not routable
BROADCAST_IPV4 | 255.255.255.255 | Broadcast address (IPv4)
EXAMPLE | example.com | Example domain for documentation

In case you know more commonly used `Host`s do feel free to add some more.

**Comment by NOOMA-42** [comment]
Hi I just made a pr to this issue, please let me know if you have any feedback

**Comment by GlenDC** [comment]
Hi @NOOMA-42 thank you for the interest. I'll assign the isuse to you already and review your PR promptly. Happy holidays and take care!

**Comment by GlenDC** [comment]
Closed by @NOOMA-42 in https://github.com/plabayo/rama/pull/367.
