### ISSUE TITLE
support boringssl support

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#55]
especially for the client side this is needed to emulate TLS using boringssl directly (for chromium profiles)

**Comment by AlvinKuruvilla** [comment]
Hey Glen, I want to take a stab at this one, but I'm not really sure where to begin. I noticed we do have [rustls client](https://github.com/plabayo/rama/tree/main/src/tls/rustls/client) so I figured it may be similar to that but other than that, I'm not sure how to proceed.

**Comment by AlvinKuruvilla** [comment]
I agree with you  and I appreciate the details you provided.
