### ISSUE TITLE
Provide support for boxed custom matchers in layer enums

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#92]
For both stream (L4) and http layers we have enums to allow for single type groupings. As an escape hatch might be good to allow custom boxed variants as well.

**Comment by dmackdev** [comment]
Hi @GlenDC, could you please provide some guidance for the type of the inner field of the new enum variant?

Should we use the `Matcher` trait, so something like:
```rust
pub enum HttpMatcherKind
    //...
    Predicate(Arc<dyn crate::service::Matcher<State, Request<Body>>>)
}
```

Or the `Fn` trait, similar to how it is done in the `http::layer::cors` module, e.g. [here](https://github.com/plabayo/rama/blob/main/src/http/layer/cors/allow_credentials.rs#L88)? Would this need as arguments all the arguments in the `Matcher::matches` trait method, or just the `Request`?

Is it correct that this change will require introducing generics for `HttpMatcherKind` and `HttpMatcher`, in order for the `Body` parameter to align with their `Matcher` trait implementations?

**Comment by GlenDC** [comment]
I would do it like this:

```rust
pub enum HttpMatcherKind<State, Body> {
    //...
    Custom(Box<dyn crate::service::Matcher<State, Request<Body>>>)
}
```

So a `Box` instead of an `Arc`, and I would call it `Custom` or something like that.

It does indeed also mean that you'll need to introduce generic parameters, not much that can be done about that.
Let me know if introducing that gives difficulties in some use cases @dmackdev , we can always give this some more thought if it does. I think it should be okay as those parameters should be able to be inferred in any use case I can think of, e.g. it's not much different of how many Services require this knowledge as well.

Other then that you're good to go. Thanks again.

**Comment by dmackdev** [comment]
I've attempted to add the `Custom` variant https://github.com/dmackdev/rama/pull/1, but I am running into some issues - I have left some comments on that PR. Would appreciate some guidance @GlenDC.

**Comment by GlenDC** [comment]
> I've attempted to add the `Custom` variant in this PR: [dmackdev#1](https://github.com/dmackdev/rama/pull/1). I have branched off of https://github.com/dmackdev/rama/tree/add-http-matcher-methods. But I am running into some issues - I have left some comments on that PR. Would appreciate some guidance @GlenDC.

Awesome work @dmackdev . Seeing the progress makes me happy. I left comments and a review behind on your pull request. I hope this serves as sufficient guidance. But if something is still not clear, or you want to spar some ideas or other feedback, do let me know. All good.

**Comment by GlenDC** [comment]
The work for the Http layer has been completed by @dmackdev for this story.

@dmackdev do you also want to tackle the same work but for the transport layer, or do you prefer to pass that to someone else? Up to you!

**Comment by dmackdev** [comment]
@GlenDC I can pick this up for the transport layer too.

**Comment by GlenDC** [comment]
Great! All yours and thank you for that!
