### ISSUE TITLE
Provide “and(matcher)” and “or(matcher)” methods to enum matchers

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#93]
We already have in these http/stream enum matchers `and_*` and `or_*` methods. However currently there is no way to do complex chaining for the matcher of that passed in argument.

eg you can’t chain these, or negate them.

Before:

```rust
HttpMatcher::method(get).and_header(“foo”).negate()
```

the above is wrong as you would get `!(M AND H)`, instead of the desired `M AND !H`, which now would be possible as a result of completing this issue:

```rust
HttpMatcher::method(get).and(HttpMatcher::header(“foo”).negate())
```

Same applies to the stream/L4 enum matcher.

**Comment by dmackdev** [comment]
Hi @GlenDC, I would be interested in picking this up.

Could you clarify what you mean that the first example is wrong? I think the resulting expression `!(M AND H)`is the expected behaviour from the way the code reads. 

Are you just saying that there is currently no way to express the second expression `M AND !H` using the current builder methods?

**Comment by GlenDC** [comment]
Feel free to pick it up @dmackdev, is all yours. And that is correct. Currently there is indeed no way to express `M AND !H`. 

You can already express `!M AND H`, as that is something like `matcher_a().negate().and_matcher_b()` (sorry for the pseudo code).

But `X AND !Y` is indeed impossible given that `matcher_x().and_matcher_y().negate` will instead be equal to `!(X AND Y)`, which equals to `!X OR !Y`. Either way, not what you might have desired.

So @dmackdev you are correct that it's not that the first example is wrong, my wording was a bit too strong there. It's more like you say yourself, there is currently no way to express the negation of the other one. Of course we could also provide `and_matcher_x_negate` for each method. However there are also other constructions that are currently not possible.

So providing `and` and `or` methods to accept the `Enum` matcher directly solves all those cases. And once someone also tackles #92 we can also support in the same enum any custom matcher as well. But that's a different ticket. Of course if you wish feel free to pick them up together if you have the time/energy/desire and do it in one PR if you wish. All good for me.

**Comment by GlenDC** [comment]
So the issue is all yours @dmackdev. If you do decide to not pick it up, do let it be known. Otherwise have fun. You can ask questions or guidance here, via email or discord. Input, remarks, feedback can be given the same way. Thanks for your time, energy and effort.

**Comment by dmackdev** [comment]
If the current matcher was not negated and we were `AND`ing with an `AND` already, I think it would be safe to append the new matcher like so:
```rust
    pub fn and(mut self, matcher: HttpMatcher) -> Self {
        match (self.negate, &mut self.kind) {
            (false, HttpMatcherKind::All(v)) => {
                v.push(matcher);
                self
            }
            _ => HttpMatcher {
                kind: HttpMatcherKind::All(vec![self, matcher]),
                negate: false,
            },
        }
    }
```

**Comment by GlenDC** [comment]
Awesome, good thinking over there.

- you’re correct, if that test was run as you have written then that is indeed a bug
- Regarding your plan described in the other comments, fully agreed with it. I’m very happy with that approach.

you are free to implement it like that. Please do also add sufficient tests for it if you can.

regarding the bug. Do you mind fixing it as part of this work, or do you prefer that I log it as a separate ticket to be done separately? Do let me know if you can

thanks already a lot for your initiative and work. This is very much appreciated!

**Comment by dmackdev** [comment]
Thanks for the feedback and confirmation! Glad to be of help.

My proposed approach will also fix the bug, so no need to create a separate ticket, unless you specifically want to track the bug.

You can assign this issue to me, and I will get a PR up soon.

**Comment by GlenDC** [comment]
Unfortunately I do not think github allows to assign non members to a ticket i think. I’ll check again tonight.

and yes. while I was in the park with my youngest kid I realised that your approach would indeed fix the bug as well. So no, no need to track or do it separately. Please do add an explicit test for it.

looking forward to your PR!

**Comment by dmackdev** [comment]
No problem!

I have started the PR https://github.com/plabayo/rama/pull/130 - keen to know your thoughts!

I have added some tests, but I was thinking that a custom boxed matcher from https://github.com/plabayo/rama/issues/92 would be quite useful - for testing, custom matchers that just return true/false without inspecting the request could be used, to purely test the boolean logic of the `HttpMatcher`.

**Comment by GlenDC** [comment]
This issue also mentions to do the same work that you do in #130, @dmackdev , but then for the `SocketMatcher` (transport layer). However, I would keep that for a separate PR, and given the state of your PR it seems you agree with that. Of course if you do not feel you have the energy or desire to also do the second part in a new PR, then feel free to let it be known and someone else can do that.

Same goes for #92.

**Comment by GlenDC** [comment]
The work for the Http layer has been completed by @dmackdev for this story.

@dmackdev do you also want to tackle the same work but for the transport layer, or do you prefer to pass that to someone else? Up to you!

**Comment by dmackdev** [comment]
@GlenDC I can pick this up for the transport layer too.

**Comment by GlenDC** [comment]
Great! All yours and thank you for that!
